export const shoePricing = [
    {
        id: 1,
        brand: "Nike",
        model: "Air Max 270",
        price: 150,
        currency: "USD",
    },
    {
        id: 2,
        brand: "Adidas",
        model: "Ultraboost 21",
        price: 180,
        currency: "USD",
    },
    {
        id: 3,
        brand: "Puma",
        model: "RS-X3",
        price: 110,
        currency: "USD",
    },
    {
        id: 4,
        brand: "Reebok",
        model: "Nano X1",
        price: 130,
        currency: "USD",
    },
    {
        id: 5,
        brand: "New Balance",
        model: "Fresh Foam 1080v11",
        price: 160,
        currency: "USD",
    },
    {
        id: 6,
        brand: "Asics",
        model: "Gel-Kayano 28",
        price: 155,
        currency: "USD",
    },
    {
        id: 7,
        brand: "Under Armour",
        model: "HOVR Phantom 2",
        price: 140,
        currency: "USD",
    },
    {
        id: 8,
        brand: "Converse",
        model: "Chuck Taylor All Star",
        price: 60,
        currency: "USD",
    },
    {
        id: 9,
        brand: "Vans",
        model: "Old Skool",
        price: 65,
        currency: "USD",
    },
    {
        id: 10,
        brand: "Jordan",
        model: "Air Jordan 1",
        price: 170,
        currency: "USD",
    },
];
